#!/usr/bin/env python3
"""
json_to_spice.py
Convert a minimal circuit JSON (ui/example_circuit.json) into a SPICE netlist file (circuit.sp)
Writes out circuit.sp
"""
import json
import sys
from pathlib import Path

def make_netlist(circuit_json, out_path="circuit.sp"):
    comp_lines = []
    # assign node names mapping for SPICE (use provided nodes)
    # AC source V1 n_ac 0 SIN(0 Vpeak freq) ; note SPICE's SIN uses Voffset Vamp Freq
    # We'll convert RMS amplitude to Vpeak: Vpeak = Vrms * sqrt(2)
    vcnt = 1
    rcnt = 1
    scnt = 1
    nodes = set()
    for comp in circuit_json.get("components", []):
        typ = comp["type"].upper()
        if typ == "AC":
            amp = float(comp["params"].get("amplitude", 230.0))
            freq = float(comp["params"].get("freq", 50.0))
            vpeak = amp * (2**0.5)
            n1, n2 = comp["nodes"]
            nodes.add(n1); nodes.add(n2)
            # V1 label fixed to Vsource
            comp_lines.append(f"V{vcnt} {n1} {n2} SIN(0 {vpeak} {freq})")
            vcnt += 1
        elif typ == "RES":
            val = comp["params"].get("resistance", 100.0)
            n1, n2 = comp["nodes"]
            comp_lines.append(f"R{rcnt} {n1} {n2} {val}")
            rcnt += 1
        elif typ == "SWITCH":
            # simple voltage-controlled switch using S element with control source
            # We'll implement using a voltage-controlled switch: Sxxx N+ N- NC+ NC- modelname
            n1, n2 = comp["nodes"]
            on_r = comp["params"].get("on_res", 0.01)
            off_r = comp["params"].get("off_res", 1e9)
            # define a small Vcontrol source between nodes 'ctrl_{id}_p' and 0; we'll tie control high later if needed
            model = f"SWMODEL{scnt}"
            comp_lines.append(f"S{scnt} {n1} {n2} ctl{scnt} 0 {model}")
            # control voltage source (we will set to 0 or 5 later by an independent source)
            comp_lines.append(f"VCTL{scnt} ctl{scnt} 0 PULSE(0 5 0 1u 1u 10u 20u)")
            # model
            comp_lines.append(f".model {model} SW(Ron={on_r} Roff={off_r})")
            scnt += 1
        else:
            # unknown: comment
            comp_lines.append(f"* Unknown component type: {comp}")
    # measurement commands: write node voltages for mapped nodes and currents through voltage source V1
    mapping = circuit_json.get("mappings", {})
    sim = circuit_json.get("simulation", {})
    duration = sim.get("duration", 0.1)
    timestep = sim.get("timestep", 1e-4)
    # safe header
    netlist = ["* Generated by json_to_spice.py", ".option numdgt=8", ".option post=2"]
    netlist.extend(comp_lines)
    # transient
    netlist.append(f".tran {timestep} {duration}")
    # write data to CSV using WRDATA (ngspice supports WRDATA)
    # columns: time and any mapped nodes plus currents through sources V1..Vn
    write_cols = ["time"]
    # voltage sensors
    if "voltage_sensor_node" in mapping:
        write_cols.append(f"V({mapping['voltage_sensor_node']})")
    if "current_shunt" in mapping:
        # identify which resistor corresponds to shunt: netlist has R1.. etc; we will write current through that resistor by name
        # NOTE: we require the user mark the shunt component id string equal to the name in components list (we will look up)
        shunt_id = mapping['current_shunt']
        # try to find resistor name: assume R<idx> and component had been second added maybe not straightforward
        # Simplify: user can also include mapping.current_shunt_name which is the resistor label (e.g., R1). Fallback use I(V1)
        if mapping.get("current_shunt_name"):
            write_cols.append(f"I({mapping['current_shunt_name']})")
        else:
            # fallback current through first voltage source V1
            write_cols.append("I(V1)")
    if "relay_node" in mapping:
        write_cols.append(f"V({mapping['relay_node']})")
    if "temperature_node" in mapping:
        write_cols.append(f"V({mapping['temperature_node']})")
    # Use wrdata to write CSV
    cols_str = " ".join(write_cols)
    netlist.append(f".print tran {cols_str}")
    # Also add a directive to save raw data
    netlist.append(f".save all")
    netlist.append(".end")
    out_text = "\n".join(netlist)
    Path(out_path).write_text(out_text)
    print(f"Wrote netlist to {out_path}")

if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--json", "-j", default=r"D:\INSTINCT4.0\equip\ui\example_circuit.json")
    p.add_argument("--out", "-o", default="circuit.sp")
    args = p.parse_args()
    cj = json.load(open(args.json))
    make_netlist(cj, args.out)
